__init__ = ["AttitudeUI_savejsondict","AttitudeUI_loadjsondict"]
def AttitudeUI_savejsondict(self,jdict):
   '''Autogenerated code from ui's make/awk trick.'''
   jdict['attitude_xText'] = self.attitude_xText.text()
   jdict['attitude_yText'] = self.attitude_yText.text()
   jdict['attitude_zText'] = self.attitude_zText.text()
   jdict['coordinatesText'] = self.coordinatesText.text()
   jdict['dateobsText'] = self.dateobsText.text()
   jdict['siderealText'] = self.siderealText.text()

# def AttitudeUI_savejsondict
def AttitudeUI_loadjsondict(self,jdict):
   '''Autogenerated code from ui's make/awk trick.'''
   self.attitude_xText.setText(jdict['attitude_xText'])
   self.attitude_yText.setText(jdict['attitude_yText'])
   self.attitude_zText.setText(jdict['attitude_zText'])
   self.coordinatesText.setText(jdict['coordinatesText'])
   self.dateobsText.setText(jdict['dateobsText'])
   self.siderealText.setText(jdict['siderealText'])

# def AttitudeUI_loadjsondict
