__init__ = ["NASpectrographyUI_savejsondict","NASpectrographyUI_loadjsondict"]
def NASpectrographyUI_savejsondict(self,jdict):
   '''Autogenerated code from ui's make/awk trick.'''

# def NASpectrographyUI_savejsondict
def NASpectrographyUI_loadjsondict(self,jdict):
   '''Autogenerated code from ui's make/awk trick.'''

# def NASpectrographyUI_loadjsondict
