# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SiteUI.ui',
# licensing of 'SiteUI.ui' applies.
#
# Created: Wed Dec 16 07:57:44 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Site(object):
    def setupUi(self, Site):
        Site.setObjectName("Site")
        Site.resize(533, 168)
        self.savecancel = QtWidgets.QDialogButtonBox(Site)
        self.savecancel.setGeometry(QtCore.QRect(220, 125, 91, 32))
        self.savecancel.setOrientation(QtCore.Qt.Horizontal)
        self.savecancel.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.savecancel.setObjectName("savecancel")
        self.label = QtWidgets.QLabel(Site)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Site)
        self.label_2.setGeometry(QtCore.QRect(10, 65, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Site)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.label_3.setObjectName("label_3")
        self.obsgeo_b = QtWidgets.QLineEdit(Site)
        self.obsgeo_b.setGeometry(QtCore.QRect(120, 40, 121, 23))
        self.obsgeo_b.setObjectName("obsgeo_b")
        self.obsgeo_l = QtWidgets.QLineEdit(Site)
        self.obsgeo_l.setGeometry(QtCore.QRect(120, 65, 121, 23))
        self.obsgeo_l.setObjectName("obsgeo_l")
        self.obsgeo_h = QtWidgets.QLineEdit(Site)
        self.obsgeo_h.setGeometry(QtCore.QRect(120, 90, 121, 23))
        self.obsgeo_h.setObjectName("obsgeo_h")
        self.label_4 = QtWidgets.QLabel(Site)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_4.setObjectName("label_4")
        self.currentSite = QtWidgets.QLineEdit(Site)
        self.currentSite.setGeometry(QtCore.QRect(210, 10, 311, 23))
        self.currentSite.setObjectName("currentSite")
        self.siteSelect = QtWidgets.QComboBox(Site)
        self.siteSelect.setGeometry(QtCore.QRect(120, 10, 79, 23))
        self.siteSelect.setCurrentText("")
        self.siteSelect.setObjectName("siteSelect")
        self.saveButton = QtWidgets.QPushButton(Site)
        self.saveButton.setGeometry(QtCore.QRect(10, 130, 80, 23))
        self.saveButton.setObjectName("saveButton")
        self.label_5 = QtWidgets.QLabel(Site)
        self.label_5.setGeometry(QtCore.QRect(250, 65, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Site)
        self.label_6.setGeometry(QtCore.QRect(250, 90, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Site)
        self.label_7.setGeometry(QtCore.QRect(250, 40, 101, 21))
        self.label_7.setObjectName("label_7")
        self.helpButton = QtWidgets.QPushButton(Site)
        self.helpButton.setGeometry(QtCore.QRect(435, 130, 80, 23))
        self.helpButton.setObjectName("helpButton")
        self.usersiteGroup = QtWidgets.QGroupBox(Site)
        self.usersiteGroup.setGeometry(QtCore.QRect(335, 35, 181, 76))
        self.usersiteGroup.setObjectName("usersiteGroup")
        self.addUserSite = QtWidgets.QPushButton(self.usersiteGroup)
        self.addUserSite.setGeometry(QtCore.QRect(100, 25, 80, 23))
        self.addUserSite.setObjectName("addUserSite")
        self.userSiteCombo = QtWidgets.QComboBox(self.usersiteGroup)
        self.userSiteCombo.setGeometry(QtCore.QRect(10, 50, 171, 23))
        self.userSiteCombo.setObjectName("userSiteCombo")

        self.retranslateUi(Site)
        QtCore.QObject.connect(self.savecancel, QtCore.SIGNAL("accepted()"), Site.accept)
        QtCore.QObject.connect(self.savecancel, QtCore.SIGNAL("rejected()"), Site.reject)
        QtCore.QMetaObject.connectSlotsByName(Site)

    def retranslateUi(self, Site):
        Site.setWindowTitle(QtWidgets.QApplication.translate("Site", "Site", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Site", "Longitude", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Site", "Latitude", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Site", "Altitude [m]", None, -1))
        self.obsgeo_b.setToolTip(QtWidgets.QApplication.translate("Site", "Longitude (negative for West)", None, -1))
        self.obsgeo_l.setToolTip(QtWidgets.QApplication.translate("Site", "Latitude", None, -1))
        self.obsgeo_h.setToolTip(QtWidgets.QApplication.translate("Site", "Alitiude", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Site", "Observatory", None, -1))
        self.currentSite.setToolTip(QtWidgets.QApplication.translate("Site", "Observatory Name", None, -1))
        self.currentSite.setPlaceholderText(QtWidgets.QApplication.translate("Site", "Sommers-Bausch Observatory, Boulder", None, -1))
        self.siteSelect.setToolTip(QtWidgets.QApplication.translate("Site", "Observatory Code", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("Site", "Save", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Site", "OBSGEO-B", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Site", "OBSGEO-H", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Site", "OBSGEO-L", None, -1))
        self.helpButton.setText(QtWidgets.QApplication.translate("Site", "Help", None, -1))
        self.usersiteGroup.setTitle(QtWidgets.QApplication.translate("Site", "User Sites", None, -1))
        self.addUserSite.setText(QtWidgets.QApplication.translate("Site", "add", None, -1))

