# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpectrographUI.ui',
# licensing of 'SpectrographUI.ui' applies.
#
# Created: Wed Dec 16 07:57:44 2020
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Spectrograph(object):
    def setupUi(self, Spectrograph):
        Spectrograph.setObjectName("Spectrograph")
        Spectrograph.resize(540, 619)
        Spectrograph.setStyleSheet("")
        self.temperatureBox = QtWidgets.QGroupBox(Spectrograph)
        self.temperatureBox.setGeometry(QtCore.QRect(20, 340, 501, 80))
        self.temperatureBox.setObjectName("temperatureBox")
        self.temp1Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp1Value.setEnabled(False)
        self.temp1Value.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.temp1Value.setObjectName("temp1Value")
        self.temp1Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp1Label.setGeometry(QtCore.QRect(10, 30, 59, 15))
        self.temp1Label.setObjectName("temp1Label")
        self.temp2Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp2Label.setGeometry(QtCore.QRect(80, 30, 59, 15))
        self.temp2Label.setObjectName("temp2Label")
        self.temp3Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp3Label.setGeometry(QtCore.QRect(150, 30, 59, 15))
        self.temp3Label.setObjectName("temp3Label")
        self.temp4Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp4Label.setGeometry(QtCore.QRect(220, 30, 59, 15))
        self.temp4Label.setObjectName("temp4Label")
        self.temp5Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp5Label.setGeometry(QtCore.QRect(290, 30, 59, 15))
        self.temp5Label.setObjectName("temp5Label")
        self.temp2Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp2Value.setEnabled(False)
        self.temp2Value.setGeometry(QtCore.QRect(80, 50, 61, 23))
        self.temp2Value.setObjectName("temp2Value")
        self.temp3Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp3Value.setEnabled(False)
        self.temp3Value.setGeometry(QtCore.QRect(150, 50, 61, 23))
        self.temp3Value.setObjectName("temp3Value")
        self.temp4Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp4Value.setEnabled(False)
        self.temp4Value.setGeometry(QtCore.QRect(220, 50, 61, 23))
        self.temp4Value.setObjectName("temp4Value")
        self.temp5Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp5Value.setEnabled(False)
        self.temp5Value.setGeometry(QtCore.QRect(290, 50, 61, 23))
        self.temp5Value.setObjectName("temp5Value")
        self.temp6Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp6Label.setGeometry(QtCore.QRect(360, 30, 59, 15))
        self.temp6Label.setObjectName("temp6Label")
        self.temp6Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp6Value.setEnabled(False)
        self.temp6Value.setGeometry(QtCore.QRect(360, 50, 61, 23))
        self.temp6Value.setObjectName("temp6Value")
        self.temp7Label = QtWidgets.QLabel(self.temperatureBox)
        self.temp7Label.setGeometry(QtCore.QRect(430, 30, 71, 16))
        self.temp7Label.setObjectName("temp7Label")
        self.temp7Value = QtWidgets.QLineEdit(self.temperatureBox)
        self.temp7Value.setEnabled(False)
        self.temp7Value.setGeometry(QtCore.QRect(430, 50, 61, 23))
        self.temp7Value.setObjectName("temp7Value")
        self.lampsBox = QtWidgets.QGroupBox(Spectrograph)
        self.lampsBox.setGeometry(QtCore.QRect(20, 240, 111, 91))
        self.lampsBox.setObjectName("lampsBox")
        self.compLampSwitch = QtWidgets.QCheckBox(self.lampsBox)
        self.compLampSwitch.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.compLampSwitch.setObjectName("compLampSwitch")
        self.flatLampSwitch = QtWidgets.QCheckBox(self.lampsBox)
        self.flatLampSwitch.setGeometry(QtCore.QRect(10, 40, 85, 21))
        self.flatLampSwitch.setObjectName("flatLampSwitch")
        self.slitLampSwitch = QtWidgets.QCheckBox(self.lampsBox)
        self.slitLampSwitch.setGeometry(QtCore.QRect(10, 60, 85, 21))
        self.slitLampSwitch.setObjectName("slitLampSwitch")
        self.heatersBox = QtWidgets.QGroupBox(Spectrograph)
        self.heatersBox.setGeometry(QtCore.QRect(140, 240, 231, 91))
        self.heatersBox.setStyleSheet("")
        self.heatersBox.setObjectName("heatersBox")
        self.heater1Switch = QtWidgets.QCheckBox(self.heatersBox)
        self.heater1Switch.setGeometry(QtCore.QRect(10, 40, 85, 21))
        self.heater1Switch.setObjectName("heater1Switch")
        self.heater1SetPoint = QtWidgets.QLineEdit(self.heatersBox)
        self.heater1SetPoint.setGeometry(QtCore.QRect(90, 40, 61, 23))
        self.heater1SetPoint.setObjectName("heater1SetPoint")
        self.heater2Switch = QtWidgets.QCheckBox(self.heatersBox)
        self.heater2Switch.setGeometry(QtCore.QRect(10, 60, 85, 21))
        self.heater2Switch.setObjectName("heater2Switch")
        self.heater2SetPoint = QtWidgets.QLineEdit(self.heatersBox)
        self.heater2SetPoint.setGeometry(QtCore.QRect(90, 60, 61, 23))
        self.heater2SetPoint.setObjectName("heater2SetPoint")
        self.heater1Delta = QtWidgets.QLineEdit(self.heatersBox)
        self.heater1Delta.setEnabled(False)
        self.heater1Delta.setGeometry(QtCore.QRect(160, 40, 61, 23))
        self.heater1Delta.setObjectName("heater1Delta")
        self.heater2Delta = QtWidgets.QLineEdit(self.heatersBox)
        self.heater2Delta.setEnabled(False)
        self.heater2Delta.setGeometry(QtCore.QRect(160, 60, 61, 23))
        self.heater2Delta.setObjectName("heater2Delta")
        self.heatersSetpointLabel = QtWidgets.QLabel(self.heatersBox)
        self.heatersSetpointLabel.setGeometry(QtCore.QRect(90, 20, 59, 15))
        self.heatersSetpointLabel.setObjectName("heatersSetpointLabel")
        self.heatersDeltaLabel = QtWidgets.QLabel(self.heatersBox)
        self.heatersDeltaLabel.setGeometry(QtCore.QRect(160, 20, 59, 15))
        self.heatersDeltaLabel.setObjectName("heatersDeltaLabel")
        self.motorsBox = QtWidgets.QGroupBox(Spectrograph)
        self.motorsBox.setGeometry(QtCore.QRect(20, 100, 501, 131))
        self.motorsBox.setStyleSheet("")
        self.motorsBox.setObjectName("motorsBox")
        self.gratingOffset = QtWidgets.QLineEdit(self.motorsBox)
        self.gratingOffset.setEnabled(False)
        self.gratingOffset.setGeometry(QtCore.QRect(330, 98, 61, 23))
        self.gratingOffset.setObjectName("gratingOffset")
        self.rotatorOffset = QtWidgets.QLineEdit(self.motorsBox)
        self.rotatorOffset.setEnabled(False)
        self.rotatorOffset.setGeometry(QtCore.QRect(330, 40, 61, 23))
        self.rotatorOffset.setObjectName("rotatorOffset")
        self.gratingLabel = QtWidgets.QLabel(self.motorsBox)
        self.gratingLabel.setGeometry(QtCore.QRect(10, 98, 59, 15))
        self.gratingLabel.setObjectName("gratingLabel")
        self.rotatorLabel = QtWidgets.QLabel(self.motorsBox)
        self.rotatorLabel.setGeometry(QtCore.QRect(10, 40, 59, 15))
        self.rotatorLabel.setObjectName("rotatorLabel")
        self.focusLabel = QtWidgets.QLabel(self.motorsBox)
        self.focusLabel.setGeometry(QtCore.QRect(10, 70, 59, 15))
        self.focusLabel.setObjectName("focusLabel")
        self.gratingHome = QtWidgets.QPushButton(self.motorsBox)
        self.gratingHome.setGeometry(QtCore.QRect(70, 100, 51, 21))
        self.gratingHome.setObjectName("gratingHome")
        self.focusSteps = QtWidgets.QSpinBox(self.motorsBox)
        self.focusSteps.setGeometry(QtCore.QRect(230, 70, 61, 24))
        self.focusSteps.setObjectName("focusSteps")
        self.rotatorSteps = QtWidgets.QSpinBox(self.motorsBox)
        self.rotatorSteps.setGeometry(QtCore.QRect(230, 40, 61, 24))
        self.rotatorSteps.setStyleSheet("")
        self.rotatorSteps.setObjectName("rotatorSteps")
        self.focusHome = QtWidgets.QPushButton(self.motorsBox)
        self.focusHome.setGeometry(QtCore.QRect(70, 70, 51, 23))
        self.focusHome.setObjectName("focusHome")
        self.gratingSteps = QtWidgets.QSpinBox(self.motorsBox)
        self.gratingSteps.setGeometry(QtCore.QRect(230, 98, 61, 24))
        self.gratingSteps.setObjectName("gratingSteps")
        self.rotatorHome = QtWidgets.QPushButton(self.motorsBox)
        self.rotatorHome.setGeometry(QtCore.QRect(70, 40, 51, 23))
        self.rotatorHome.setObjectName("rotatorHome")
        self.focusOffset = QtWidgets.QLineEdit(self.motorsBox)
        self.focusOffset.setEnabled(False)
        self.focusOffset.setGeometry(QtCore.QRect(330, 70, 61, 23))
        self.focusOffset.setObjectName("focusOffset")
        self.stepcountLabel = QtWidgets.QLabel(self.motorsBox)
        self.stepcountLabel.setGeometry(QtCore.QRect(230, 20, 81, 16))
        self.stepcountLabel.setObjectName("stepcountLabel")
        self.offsetLabel = QtWidgets.QLabel(self.motorsBox)
        self.offsetLabel.setGeometry(QtCore.QRect(330, 20, 81, 16))
        self.offsetLabel.setObjectName("offsetLabel")
        self.rotatorIncrease = QtWidgets.QToolButton(self.motorsBox)
        self.rotatorIncrease.setGeometry(QtCore.QRect(290, 40, 28, 22))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/right16x16.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.rotatorIncrease.setIcon(icon)
        self.rotatorIncrease.setObjectName("rotatorIncrease")
        self.rotatorDecrease = QtWidgets.QToolButton(self.motorsBox)
        self.rotatorDecrease.setGeometry(QtCore.QRect(200, 40, 28, 22))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/left16x16.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.rotatorDecrease.setIcon(icon1)
        self.rotatorDecrease.setObjectName("rotatorDecrease")
        self.focusDecrease = QtWidgets.QToolButton(self.motorsBox)
        self.focusDecrease.setGeometry(QtCore.QRect(200, 70, 28, 22))
        self.focusDecrease.setIcon(icon1)
        self.focusDecrease.setObjectName("focusDecrease")
        self.gratingDecrease = QtWidgets.QToolButton(self.motorsBox)
        self.gratingDecrease.setGeometry(QtCore.QRect(200, 100, 28, 22))
        self.gratingDecrease.setIcon(icon1)
        self.gratingDecrease.setObjectName("gratingDecrease")
        self.focusIncrease = QtWidgets.QToolButton(self.motorsBox)
        self.focusIncrease.setGeometry(QtCore.QRect(290, 70, 28, 22))
        self.focusIncrease.setIcon(icon)
        self.focusIncrease.setObjectName("focusIncrease")
        self.gratingIncrease = QtWidgets.QToolButton(self.motorsBox)
        self.gratingIncrease.setGeometry(QtCore.QRect(290, 100, 28, 22))
        self.gratingIncrease.setIcon(icon)
        self.gratingIncrease.setObjectName("gratingIncrease")
        self.rotatorSnapshot = QtWidgets.QLineEdit(self.motorsBox)
        self.rotatorSnapshot.setEnabled(False)
        self.rotatorSnapshot.setGeometry(QtCore.QRect(400, 40, 61, 23))
        self.rotatorSnapshot.setObjectName("rotatorSnapshot")
        self.focusSnapshot = QtWidgets.QLineEdit(self.motorsBox)
        self.focusSnapshot.setEnabled(False)
        self.focusSnapshot.setGeometry(QtCore.QRect(400, 70, 61, 23))
        self.focusSnapshot.setObjectName("focusSnapshot")
        self.gratingSnapshot = QtWidgets.QLineEdit(self.motorsBox)
        self.gratingSnapshot.setEnabled(False)
        self.gratingSnapshot.setGeometry(QtCore.QRect(400, 100, 61, 23))
        self.gratingSnapshot.setObjectName("gratingSnapshot")
        self.setRotator = QtWidgets.QToolButton(self.motorsBox)
        self.setRotator.setGeometry(QtCore.QRect(470, 40, 28, 22))
        self.setRotator.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/off16x16.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../icons/on16x16.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.setRotator.setIcon(icon2)
        self.setRotator.setObjectName("setRotator")
        self.setFocus = QtWidgets.QToolButton(self.motorsBox)
        self.setFocus.setGeometry(QtCore.QRect(470, 70, 28, 22))
        self.setFocus.setIcon(icon2)
        self.setFocus.setObjectName("setFocus")
        self.setGrating = QtWidgets.QToolButton(self.motorsBox)
        self.setGrating.setGeometry(QtCore.QRect(470, 100, 28, 22))
        self.setGrating.setIcon(icon2)
        self.setGrating.setObjectName("setGrating")
        self.refpointLabel = QtWidgets.QLabel(self.motorsBox)
        self.refpointLabel.setGeometry(QtCore.QRect(400, 20, 81, 16))
        self.refpointLabel.setObjectName("refpointLabel")
        self.rotatorAbsolute = QtWidgets.QLineEdit(self.motorsBox)
        self.rotatorAbsolute.setEnabled(True)
        self.rotatorAbsolute.setGeometry(QtCore.QRect(130, 40, 61, 23))
        self.rotatorAbsolute.setObjectName("rotatorAbsolute")
        self.focusAbsolute = QtWidgets.QLineEdit(self.motorsBox)
        self.focusAbsolute.setEnabled(True)
        self.focusAbsolute.setGeometry(QtCore.QRect(130, 70, 61, 23))
        self.focusAbsolute.setObjectName("focusAbsolute")
        self.gratingAbsolute = QtWidgets.QLineEdit(self.motorsBox)
        self.gratingAbsolute.setEnabled(True)
        self.gratingAbsolute.setGeometry(QtCore.QRect(130, 100, 61, 23))
        self.gratingAbsolute.setObjectName("gratingAbsolute")
        self.AbsoluteLabel = QtWidgets.QLabel(self.motorsBox)
        self.AbsoluteLabel.setGeometry(QtCore.QRect(130, 20, 81, 16))
        self.AbsoluteLabel.setObjectName("AbsoluteLabel")
        self.setLabel = QtWidgets.QLabel(self.motorsBox)
        self.setLabel.setGeometry(QtCore.QRect(470, 20, 51, 16))
        self.setLabel.setObjectName("setLabel")
        self.rotatorBox = QtWidgets.QGroupBox(Spectrograph)
        self.rotatorBox.setGeometry(QtCore.QRect(20, 10, 501, 81))
        self.rotatorBox.setStyleSheet("")
        self.rotatorBox.setObjectName("rotatorBox")
        self.positionLabel = QtWidgets.QLabel(self.rotatorBox)
        self.positionLabel.setGeometry(QtCore.QRect(10, 30, 59, 15))
        self.positionLabel.setStyleSheet("")
        self.positionLabel.setObjectName("positionLabel")
        self.PALabel = QtWidgets.QLabel(self.rotatorBox)
        self.PALabel.setGeometry(QtCore.QRect(80, 30, 59, 15))
        self.PALabel.setStyleSheet("")
        self.PALabel.setObjectName("PALabel")
        self.airmassLabel = QtWidgets.QLabel(self.rotatorBox)
        self.airmassLabel.setGeometry(QtCore.QRect(290, 30, 51, 16))
        self.airmassLabel.setStyleSheet("")
        self.airmassLabel.setObjectName("airmassLabel")
        self.rotatorPosition = QtWidgets.QLineEdit(self.rotatorBox)
        self.rotatorPosition.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.rotatorPosition.setObjectName("rotatorPosition")
        self.PAPosition = QtWidgets.QLineEdit(self.rotatorBox)
        self.PAPosition.setGeometry(QtCore.QRect(80, 50, 61, 23))
        self.PAPosition.setObjectName("PAPosition")
        self.airmassValue = QtWidgets.QLineEdit(self.rotatorBox)
        self.airmassValue.setEnabled(False)
        self.airmassValue.setGeometry(QtCore.QRect(290, 50, 61, 23))
        self.airmassValue.setObjectName("airmassValue")
        self.stepsLabel = QtWidgets.QLabel(self.rotatorBox)
        self.stepsLabel.setGeometry(QtCore.QRect(220, 30, 59, 15))
        self.stepsLabel.setStyleSheet("")
        self.stepsLabel.setObjectName("stepsLabel")
        self.rotatorMove = QtWidgets.QPushButton(self.rotatorBox)
        self.rotatorMove.setGeometry(QtCore.QRect(150, 50, 51, 23))
        self.rotatorMove.setObjectName("rotatorMove")
        self.rotatorAngle = QtWidgets.QSpinBox(self.rotatorBox)
        self.rotatorAngle.setGeometry(QtCore.QRect(220, 50, 61, 24))
        self.rotatorAngle.setObjectName("rotatorAngle")
        self.RAPosition = QtWidgets.QLineEdit(self.rotatorBox)
        self.RAPosition.setEnabled(False)
        self.RAPosition.setGeometry(QtCore.QRect(390, 30, 101, 23))
        self.RAPosition.setObjectName("RAPosition")
        self.DecPosition = QtWidgets.QLineEdit(self.rotatorBox)
        self.DecPosition.setEnabled(False)
        self.DecPosition.setGeometry(QtCore.QRect(390, 50, 101, 23))
        self.DecPosition.setObjectName("DecPosition")
        self.RALabel = QtWidgets.QLabel(self.rotatorBox)
        self.RALabel.setGeometry(QtCore.QRect(360, 30, 31, 16))
        self.RALabel.setStyleSheet("")
        self.RALabel.setObjectName("RALabel")
        self.DecLabel = QtWidgets.QLabel(self.rotatorBox)
        self.DecLabel.setGeometry(QtCore.QRect(360, 50, 31, 16))
        self.DecLabel.setStyleSheet("")
        self.DecLabel.setObjectName("DecLabel")
        self.slitBox = QtWidgets.QGroupBox(Spectrograph)
        self.slitBox.setGeometry(QtCore.QRect(400, 240, 120, 91))
        self.slitBox.setStyleSheet("")
        self.slitBox.setObjectName("slitBox")
        self.slitSelection = QtWidgets.QComboBox(self.slitBox)
        self.slitSelection.setGeometry(QtCore.QRect(0, 20, 111, 23))
        self.slitSelection.setObjectName("slitSelection")
        self.horizontalSlider = QtWidgets.QSlider(self.slitBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 60, 111, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.closeButton = QtWidgets.QDialogButtonBox(Spectrograph)
        self.closeButton.setEnabled(True)
        self.closeButton.setGeometry(QtCore.QRect(230, 590, 91, 24))
        self.closeButton.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.closeButton.setObjectName("closeButton")
        self.spectrographBox = QtWidgets.QGroupBox(Spectrograph)
        self.spectrographBox.setGeometry(QtCore.QRect(20, 420, 551, 161))
        self.spectrographBox.setStyleSheet("")
        self.spectrographBox.setObjectName("spectrographBox")
        self.spectroLog = QtWidgets.QPlainTextEdit(self.spectrographBox)
        self.spectroLog.setEnabled(True)
        self.spectroLog.setGeometry(QtCore.QRect(0, 20, 501, 141))
        self.spectroLog.setObjectName("spectroLog")

        self.retranslateUi(Spectrograph)
        QtCore.QMetaObject.connectSlotsByName(Spectrograph)

    def retranslateUi(self, Spectrograph):
        Spectrograph.setWindowTitle(QtWidgets.QApplication.translate("Spectrograph", "Spectrograph", None, -1))
        self.temperatureBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Temperatures", None, -1))
        self.temp1Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Heater 1", None, -1))
        self.temp2Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Heater 2", None, -1))
        self.temp3Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Grating", None, -1))
        self.temp4Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Slit", None, -1))
        self.temp5Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Case", None, -1))
        self.temp6Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Ambient", None, -1))
        self.temp7Label.setText(QtWidgets.QApplication.translate("Spectrograph", "Processor", None, -1))
        self.lampsBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Lamps", None, -1))
        self.compLampSwitch.setText(QtWidgets.QApplication.translate("Spectrograph", "Comp", None, -1))
        self.flatLampSwitch.setText(QtWidgets.QApplication.translate("Spectrograph", "Flat", None, -1))
        self.slitLampSwitch.setText(QtWidgets.QApplication.translate("Spectrograph", "Slit", None, -1))
        self.heatersBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Heaters", None, -1))
        self.heater1Switch.setText(QtWidgets.QApplication.translate("Spectrograph", "Heater 1", None, -1))
        self.heater2Switch.setText(QtWidgets.QApplication.translate("Spectrograph", "Heater 2", None, -1))
        self.heatersSetpointLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Setpoint", None, -1))
        self.heatersDeltaLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Delta-T", None, -1))
        self.motorsBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Motors", None, -1))
        self.gratingLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Grating", None, -1))
        self.rotatorLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Rotator", None, -1))
        self.focusLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Focus", None, -1))
        self.gratingHome.setText(QtWidgets.QApplication.translate("Spectrograph", "Home", None, -1))
        self.focusHome.setText(QtWidgets.QApplication.translate("Spectrograph", "Home", None, -1))
        self.rotatorHome.setText(QtWidgets.QApplication.translate("Spectrograph", "Home", None, -1))
        self.stepcountLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Step Count", None, -1))
        self.offsetLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Offset", None, -1))
        self.rotatorIncrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.rotatorDecrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.focusDecrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.gratingDecrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.focusIncrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.gratingIncrease.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.setRotator.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.setFocus.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.setGrating.setText(QtWidgets.QApplication.translate("Spectrograph", "...", None, -1))
        self.refpointLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Ref Point", None, -1))
        self.AbsoluteLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Absolute", None, -1))
        self.setLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Set", None, -1))
        self.rotatorBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Rotator", None, -1))
        self.positionLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Position", None, -1))
        self.PALabel.setText(QtWidgets.QApplication.translate("Spectrograph", "PA", None, -1))
        self.airmassLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Airmass", None, -1))
        self.stepsLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Steps", None, -1))
        self.rotatorMove.setText(QtWidgets.QApplication.translate("Spectrograph", "Move", None, -1))
        self.RALabel.setText(QtWidgets.QApplication.translate("Spectrograph", "RA", None, -1))
        self.DecLabel.setText(QtWidgets.QApplication.translate("Spectrograph", "Dec", None, -1))
        self.slitBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Slit", None, -1))
        self.spectrographBox.setTitle(QtWidgets.QApplication.translate("Spectrograph", "Spectrograph Log", None, -1))

